### ISSUE TITLE
Check if numbers are in AP

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/python-practice#11]
Problem - Given 3 integers, check if they are in Arithmetic progression or not.

Sample Input -
```
1 2 3
```
Sample Output -
```
yes
```

Sample Input -
```
3 2 1
```
Sample Output -
```
yes
```

**Comment by ThomasMatthewEvans** [comment]
Hi, I have created an answer for this, however the user must enter each integer independantly. Is this ok or is there a way to enter each integer at once? I've copied the cone below for your consultation.

# Authored by - Matthew Everson, https://github.com/ThomasMatthewEvans

Number1 = int(input("Enter a number:"))
Number2 = int(input("Enter a second number:"))
Number3 = int(input("Enter a third number:"))

if (Number1 == Number2 +1 or Number1 == Number2-1) and (Number1==Number3+2 or Number1 == Number3-2):
    print ("Yes")
else:
    print("No")

**Comment by VamsiSangam** [comment]
This format of input is fine. You may want to check your conditions. Your code will fail for input -

```
0 5 10
```

**Comment by ThomasMatthewEvans** [comment]
Thanks, think I've corrected now. I will make  a PR for you to review.
