### ISSUE TITLE
Lengths of words in a sentence

### ISSUE THREAD

**Issue by VamsiSangam** [VamsiSangam/python-practice#4]
Problem - Write a program which accepts a line of text and prints out each word (split by space) and its length.

Sample Input -

```
This is a small sentence
```

Sample Output -
```
This 4
is 2
a 1
small 5
sentence 8
```

**Comment by ThomasMatthewEvans** [comment]
Hi, I think I have the answer to this. 

I shall add the code below.

sentence=input("Please enter a sentence!: ")
for i in sentence.split():
    print (i +" " + str(len(i)))

**Comment by VamsiSangam** [comment]
That's correct! Add your solution to a ``` .py ``` file in the ``` Practice ``` folder and submit a PR. And do add your name on the top in comments. So your file would look something like this -

``` python
# Authored by - Matthew Everson, https://github.com/ThomasMatthewEvans
sentence=input("Please enter a sentence!: ")
for i in sentence.split():
	print (i +" " + str(len(i)))
```

And try to use more descriptive variables. Try to use ``` word ``` instead of ``` i ```. Looking forward for your PR :smile:
